Added flag to turn of build with Python.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -11,15 +11,16 @@ CMAKE="cmake"
 CMAKE_ONLY="no"
 HELP="no"
 VERBOSE=""
-OFFLINE_BUILD="no"
 
 WITH_CLANG="no"
+WITH_MPI="yes"
 WITH_CUDA="yes"
 WITH_CUDA_ARCH="auto"
 WITH_OPENMP="yes"
 WITH_TESTS="yes"
 WITH_COVERAGE="no"
 WITH_EXAMPLES="yes"
+WITH_TOOLS="yes"
 
 WITH_TEMPLATE_INSTANTIATION="no"
 INSTANTIATE_LONG_INT="no"
@@ -41,9 +42,9 @@ do
         --cmake=*                        ) CMAKE="${option#*=}" ;;
         --cmake-only=*                   ) CMAKE_ONLY="${option#*=}" ;;
         --verbose                        ) VERBOSE="VERBOSE=1" ;;
-        --offline-build                  ) OFFLINE_BUILD="yes" ;;
         --help                           ) HELP="yes" ;;
         --with-clang=*                   ) WITH_CLANG="${option#*=}" ;;
+        --with-mpi=*                     ) WITH_MPI="${option#*=}" ;;
         --with-mic=*                     ) WITH_MIC="${option#*=}" ;;
         --with-cuda=*                    ) WITH_CUDA="${option#*=}" ;;
         --with-cuda-arch=*               ) WITH_CUDA_ARCH="${option#*=}";;
@@ -51,6 +52,8 @@ do
         --with-tests=*                   ) WITH_TESTS="${option#*=}" ;;
         --with-coverage=*                ) WITH_COVERAGE="${option#*=}" ;;
         --with-examples=*                ) WITH_EXAMPLES="${option#*=}" ;;
+        --with-tools=*                   ) WITH_TOOLS="${option#*=}" ;;
+        --with-python=*                  ) WITH_PYTHON="${option#*=}" ;;
         --with-templates-instantiation=* ) WITH_TEMPLATE_INSTANTIATION="${option#*=}" ;;
         --instantiate-long-int=*         ) INSTANTIATE_LONG_INT="${option#*=}" ;;
         --instantiate-int=*              ) INSTANTIATE_INT="${option#*=}" ;;
@@ -78,13 +81,16 @@ then
     echo "   --build-jobs=NUM                      Number of processes to be used for the build. It is set to the number of available CPU cores by default."
     echo "   --prefix=PATH                         Prefix for the installation directory. ${HOME}/local by default."
     echo "   --install=yes/no                      Enables the installation of TNL files."
-    echo "   --with-mic=yes/no                     Enable MIC (Intel Xeon Phi). 'no' by default (Intel Compiler required)."
-    echo "   --with-cuda=yes/no                    Enable CUDA. 'yes' by default (CUDA Toolkit is required)."
-    echo "   --with-cuda-arch=all/auto/30/35/...   Choose CUDA architecture. 'auto' by default."
-    echo "   --with-openmp=yes/no                  Enable OpenMP. 'yes' by default."
-    echo "   --with-tests=yes/no                   Enable unit tests. 'yes' by default."
-    echo "   --with-coverage=yes/no                Enable code coverage reports for unit tests. 'no' by default (lcov is required)."
+    echo "   --with-mpi=yes/no                     Enables MPI. 'no' by default (Intel Compiler required)."
+    echo "   --with-mic=yes/no                     Enables MIC (Intel Xeon Phi). 'no' by default (Intel Compiler required)."
+    echo "   --with-cuda=yes/no                    Enables CUDA. 'yes' by default (CUDA Toolkit is required)."
+    echo "   --with-cuda-arch=all/auto/30/35/...   Chooses CUDA architecture. 'auto' by default."
+    echo "   --with-openmp=yes/no                  Enables OpenMP. 'yes' by default."
+    echo "   --with-tests=yes/no                   Enables unit tests. 'yes' by default."
+    echo "   --with-coverage=yes/no                Enables code coverage reports for unit tests. 'no' by default (lcov is required)."
     echo "   --with-examples=yes/no                Compile the 'examples' directory. 'yes' by default."
+    echo "   --with-tools=yes/no                   Compile the 'tools' directory. 'yes' by default."
+    echo "   --with-python=yes/no                  Compile with the python bindings. 'yes' by default."
     echo "   --with-templates-instantiation=yes/no Precompiles some TNL templates during the build. 'no' by default."
     echo "   --cmake=CMAKE                         Path to cmake. 'cmake' by default."
     echo "   --verbose                             It enables verbose build."
@@ -100,13 +106,27 @@ then
    export CC=clang
 fi
 
+if test ${WITH_MPI} = "yes";
+then
+    if ! [ -x  "$(command -v mpic++)" ]; then
+       echo "Warning:mpic++ is not installed on this system. MPI support is turned off." 
+    else
+       export CXX=mpic++
+       export CUDA_HOST_COMPILER=mpic++
+    fi
+    if ! [ -x  "$(command -v mpicc)" ]; then
+       echo "Warning: mpicc is not installed on this system." 
+    else
+       export CC=mpicc
+    fi
+fi
+
 
 echo "Configuring ${BUILD} $TARGET ..."
 
 ${CMAKE} ${ROOT_DIR} \
          -DCMAKE_BUILD_TYPE=${BUILD} \
          -DCMAKE_INSTALL_PREFIX=${PREFIX} \
-         -DOFFLINE_BUILD=${OFFLINE_BUILD} \
          -DWITH_MIC=${WITH_MIC} \
          -DWITH_CUDA=${WITH_CUDA} \
          -DWITH_CUDA_ARCH=${WITH_CUDA_ARCH} \
@@ -114,6 +134,8 @@ ${CMAKE} ${ROOT_DIR} \
          -DWITH_TESTS=${WITH_TESTS} \
          -DWITH_COVERAGE=${WITH_COVERAGE} \
          -DWITH_EXAMPLES=${WITH_EXAMPLES} \
+         -DWITH_TOOLS=${WITH_TOOLS} \
+         -DWITH_PYTHON=${WITH_PYTHON} \
          -DDCMTK_DIR=${DCMTK_DIR} \
          -DWITH_TEMPLATE_INSTANTIATION=${WITH_TEMPLATE_INSTANTIATION} \
          -DINSTANTIATE_FLOAT=${INSTANTIATE_FLOAT} \
@@ -165,7 +187,7 @@ fi
 
 if test ${WITH_TESTS} = "yes";
 then
-    make test
+    make test CTEST_OUTPUT_ON_FAILURE=1
     if test $? != 0; then
         echo "Error: Some test did not pass successfuly."
     fi
