Updated script for downloading matrices from the markets

diff --git a/src/Benchmarks/scripts/get-matrices b/src/Benchmarks/scripts/get-matrices
--- a/src/Benchmarks/scripts/get-matrices
+++ b/src/Benchmarks/scripts/get-matrices
@@ -1,39 +1,36 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
-BASE="ftp://math.nist.gov/pub/MatrixMarket2/Harwell-Boeing/"
-                
-#PWD=`pwd`
-#TNL_SPARSE_MATRIX_CHECK="$PWD/tnl-sparse-matrix-check"
-#IWD="$PWD"
+# exit whenever a command fails
+set -e
 
-#source ../tnl-env-variables
-source matrix-market
-source florida-matrix-market
+# enable recursive globbing
+shopt -s globstar
 
-for link in $MM_MATRICES;
-do
-   echo "###############################################################################"
-   matrix=matrices`echo $link | sed 's/ftp:\/\/math.nist.gov\/pub//'`
-   if test ! -e $matrix;
-   then
-      echo "Getting $matrix ..."      
-      wget -x --cut-dirs=1 -P matrices -nH $link
-   else
-      echo "Matrix $matrix was already downloaded."
-   fi
-   
+matrices_base_path="./mtx_matrices"
+if [[ ! -d "$matrices_base_path" ]]; then
+   mkdir "$matrices_base_path"
+fi
+cd "$matrices_base_path"
+
+# Matrix Market: https://math.nist.gov/MatrixMarket/
+wget --mirror --continue --force-directories --include-directories=/MatrixMarket/,/pub/MatrixMarket2/ --exclude-directories="*" --accept "*.mtx.gz" "https://math.nist.gov/MatrixMarket/" || true
+
+# SuiteSparse Matrix Collection: https://sparse.tamu.edu/
+# note that we need to crawl the site where the matrices are actually stored
+# (https://sparse.tamu.edu/ links to https://suitesparse-collection-website.herokuapp.com/
+# for all download links)
+wget --mirror --continue --no-parent --force-directories -X RB,mat --accept "*.tar.gz" "https://suitesparse-collection-website.herokuapp.com/"
+
+# delete empty directories
+find math.nist.gov suitesparse-collection-website.herokuapp.com -type d -empty -delete
+
+# unzip (keep the original archive)
+for f in math.nist.gov/**/*.mtx.gz; do
+   gunzip --keep --force "$f"
 done
-
-
-for link in $FLORIDA_MM_MATRICES;
-do
-   echo "###############################################################################"
-   matrix=matrices`echo $link | sed 's/http:\/\/www.cise.ufl.edu\/research\/sparse//'`
-   if test ! -e $matrix;
-   then
-      echo "Getting $matrix ..."      
-      wget -x --cut-dirs=2 -P matrices -nH $link
-   else
-      echo "Matrix $matrix was already downloaded."   
-   fi
+for f in suitesparse-collection-website.herokuapp.com/**/*.tar.gz; do
+   pushd $(dirname "$f") >/dev/null
+   tar -xaf $(basename "$f")
+   rm -f **/*_b.mtx  # these are usualy in array format
+   popd >/dev/null
 done
